import asyncio
import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Set, Dict
import httpx

from pydantic import BaseModel, Field

from lib.config import get_config
from lib.logging import get_logger
from agents.planner_agent import ProjectBlueprint, WorkerTask

logger = get_logger("swarm_orchestrator")

class SwarmOrchestrator:
    def __init__(self, workspace_root: str):
        self.config = get_config()
        self.workspace_root = Path(workspace_root)
        self._tasks_completed: Set[str] = set()
        self._tasks_failed: Set[str] = set()

    async def execute(self, blueprint: ProjectBlueprint) -> bool:
        logger.info(f"🚀 Starting Phase 6 Swarm Orchestrator with {len(blueprint.tasks)} tasks.")
        
        # 1. Setup global workspace
        self.workspace_root.mkdir(parents=True, exist_ok=True)
        
        # 2. Write Contract to memory
        memory_dir = self.workspace_root / "core_memory"
        memory_dir.mkdir(parents=True, exist_ok=True)
        contract_path = memory_dir / "contract.md"
        contract_path.write_text(blueprint.contract)
        logger.info(f"📜 Project Contract written to {contract_path}")
        
        # 3. Setup concurrency execution based on task count
        max_workers = min(10, len(blueprint.tasks))
        if max_workers < 1:
            max_workers = 1
        semaphore = asyncio.Semaphore(max_workers)
        logger.info(f"🚀 Starting Phase 6 Swarm Orchestrator with {len(blueprint.tasks)} tasks. (Bounded: {max_workers} threads)")
        
        task_futures: Dict[str, asyncio.Future] = {
            task.task_id: asyncio.Future() for task in blueprint.tasks
        }

        async def run_worker(task: WorkerTask):
            # Wait for dependencies
            for dep in task.depends_on:
                if dep in task_futures:
                    logger.info(f"Task {task.task_id} waiting on dependency {dep}")
                    await task_futures[dep]
                    if dep in self._tasks_failed:
                        logger.error(f"Task {task.task_id} aborted because dependency {dep} failed.")
                        task_futures[task.task_id].set_result(False)
                        self._tasks_failed.add(task.task_id)
                        return

            async with semaphore:
                logger.info(f"⚙️ Starting Worker Task: {task.task_id} - {task.description}")
                
                # Setup isolated workspace (cloning current state)
                worker_dir = Path("/dev/shm/helix_workers") / task.task_id
                if worker_dir.exists():
                    shutil.rmtree(worker_dir)
                shutil.copytree(self.workspace_root, worker_dir, ignore=shutil.ignore_patterns("temp_workers", ".git", "node_modules"))
                
                try:
                    # Execute Aider via subprocess
                    env = os.environ.copy()
                    env["GEMINI_API_KEY"] = self.config.GEMINI_API_KEY
                    
                    if "HELIX_MOCK_LLM_PAYLOAD" in os.environ:
                        logger.info(f"TEST HOOK: Bypassing Aider execution for {task.task_id} to conserve API credits.")
                        await asyncio.sleep(2.0) # Simulate work latency
                        
                        if hasattr(task, 'generated_files') and task.generated_files:
                            for gen_file in task.generated_files:
                                path_str = gen_file.path if hasattr(gen_file, 'path') else gen_file['path']
                                if path_str.startswith("workspace/"):
                                    path_str = path_str[len("workspace/"):]
                                content_str = gen_file.content if hasattr(gen_file, 'content') else gen_file['content']
                                
                                mock_path = worker_dir / path_str
                                mock_path.parent.mkdir(parents=True, exist_ok=True)
                                mock_path.write_text(content_str)
                        else:
                            for target_file in task.target_files:
                                mock_path = worker_dir / target_file
                                mock_path.parent.mkdir(parents=True, exist_ok=True)
                                mock_path.write_text(f"/* Mock content for {target_file} generated by Lab Harness */")
                        
                        logger.info(f"✅ Worker {task.task_id} completed successfully (MOCKED).")
                        
                        files_to_merge = task.target_files
                        if hasattr(task, 'generated_files') and task.generated_files:
                            files_to_merge = []
                            for gen_file in task.generated_files:
                                path_str = gen_file.path if hasattr(gen_file, 'path') else gen_file['path']
                                files_to_merge.append(path_str)
                                
                        for target_file in files_to_merge:
                            clean_target = target_file[len("workspace/"):] if target_file.startswith("workspace/") else target_file
                            src = worker_dir / clean_target
                            dst = self.workspace_root / clean_target
                            if src.exists():
                                dst.parent.mkdir(parents=True, exist_ok=True)
                                shutil.copy2(src, dst)
                                logger.info(f"Merged {clean_target} from {task.task_id}")
                                
                        self._tasks_completed.add(task.task_id)
                        task_futures[task.task_id].set_result(True)
                        return

                    # TIER 3: CORRECTION (Self-Healing Loop)
                    max_retries = 3
                    current_attempt = 0
                    test_passed = False
                    feedback = ""

                    while current_attempt < max_retries and not test_passed:
                        current_attempt += 1
                        logger.info(f"Worker {task.task_id} - Attempt {current_attempt}/{max_retries}")
                        
                        aider_cmd = [
                            self.config.AIDER_BIN,
                            "--model", "gemini/gemini-2.5-flash",
                            "--no-show-model-warnings",
                            "--yes-always",
                            "--no-suggest-shell-commands",
                            "--read", str(worker_dir / "core_memory" / "contract.md")
                        ]
                        
                        if current_attempt == 1:
                            aider_cmd.extend(["--message", f"TASK ID: {task.task_id}\nDESCRIPTION: {task.description}\nTARGET FILES: {', '.join(task.target_files)}"])
                        else:
                            aider_cmd.extend(["--message", f"The previous execution failed validation. Please fix the following errors:\n{feedback}"])
                            
                        aider_cmd.extend(task.target_files)
                        
                        process = await asyncio.create_subprocess_exec(
                            *aider_cmd,
                            cwd=str(worker_dir),
                            stdout=asyncio.subprocess.PIPE,
                            stderr=asyncio.subprocess.PIPE,
                            env=env
                        )
                        
                        stdout, stderr = await asyncio.wait_for(process.communicate(), timeout=self.config.AIDER_TIMEOUT)
                        
                        if process.returncode != 0:
                            if current_attempt < max_retries:
                                feedback = f"Aider generation failed with exit code {process.returncode}:\n{stderr.decode('utf-8')[-1000:]}"
                                logger.warning(f"Worker {task.task_id} failed generation. Retrying...")
                                continue
                            else:
                                raise Exception(f"Worker {task.task_id} failed with exit code {process.returncode}")

                        # QA Validation Step (Syntax Checking)
                        validation_failed = False
                        for target_file in task.target_files:
                            if target_file.endswith(".py"):
                                file_path = worker_dir / target_file
                                if file_path.exists():
                                    val_proc = await asyncio.create_subprocess_exec(
                                        "python3", "-m", "py_compile", str(file_path),
                                        stdout=asyncio.subprocess.PIPE,
                                        stderr=asyncio.subprocess.PIPE
                                    )
                                    val_stdout, val_stderr = await val_proc.communicate()
                                    if val_proc.returncode != 0:
                                        validation_failed = True
                                        feedback = f"Syntax error in {target_file}:\n{val_stderr.decode('utf-8')}"
                                        logger.warning(f"Worker {task.task_id} generated invalid Python syntax. Retrying...")
                                        break
                                        
                        if validation_failed:
                            if current_attempt >= max_retries:
                                raise Exception(f"Worker {task.task_id} failed QA Validation after {max_retries} attempts.")
                        else:
                            test_passed = True
                    
                    logger.info(f"✅ Worker {task.task_id} completed successfully after {current_attempt} attempts.")
                    for target_file in task.target_files:
                        src = worker_dir / target_file
                        dst = self.workspace_root / target_file
                        if src.exists():
                            dst.parent.mkdir(parents=True, exist_ok=True)
                            shutil.copy2(src, dst)
                            logger.info(f"Merged {target_file} from {task.task_id}")
                            
                    self._tasks_completed.add(task.task_id)
                    task_futures[task.task_id].set_result(True)

                except Exception as e:
                    logger.error(f"❌ Worker {task.task_id} failed: {e}")
                    
                    # --- ON-FAILURE DUMP STRATEGY ---
                    dump_dir = Path("/workspaces/AirCode/crash_dumps") / task.task_id
                    if dump_dir.exists():
                        shutil.rmtree(dump_dir)
                    dump_dir.parent.mkdir(parents=True, exist_ok=True)
                    logger.warning(f"Preserving failed RAM disk workspace to persistent storage: {dump_dir}")
                    try:
                        shutil.copytree(worker_dir, dump_dir)
                    except Exception as copy_e:
                        logger.error(f"Failed to create crash dump for {task.task_id}: {copy_e}")
                    # ---------------------------------
                    
                    self._tasks_failed.add(task.task_id)
                    task_futures[task.task_id].set_result(False)
                    
                finally:
                    # Always clean up the RAM disk to prevent memory leaks on the VM
                    if worker_dir.exists():
                        try:
                            shutil.rmtree(worker_dir)
                            logger.info(f"Cleaned up RAM disk partition for {task.task_id}")
                        except Exception as e:
                            logger.error(f"Failed to cleanup RAM disk for {task.task_id}: {e}")
                            
        # 4. Launch all tasks concurrently
        execution_tasks = [asyncio.create_task(run_worker(task)) for task in blueprint.tasks]
        await asyncio.gather(*execution_tasks)
        
        logger.info(f"🏁 Swarm Execution Complete. Success: {len(self._tasks_completed)}, Failed: {len(self._tasks_failed)}")
        return len(self._tasks_failed) == 0

def get_swarm_orchestrator(workspace_root: str) -> SwarmOrchestrator:
    return SwarmOrchestrator(workspace_root)
